// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc8SAbqgen00jYP_60p4g4SaBW_I8g7AY',
    appId: '1:876289046371:web:4d36adb162f876e1934556',
    messagingSenderId: '876289046371',
    projectId: 'laci-495ab',
    authDomain: 'laci-495ab.firebaseapp.com',
    storageBucket: 'laci-495ab.appspot.com',
    measurementId: 'G-6E4XJSFDGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyW1ldamQ-G4RuRiUt5t2LuS5UYSGeD1o',
    appId: '1:876289046371:android:c5aa85d25b7d70a3934556',
    messagingSenderId: '876289046371',
    projectId: 'laci-495ab',
    storageBucket: 'laci-495ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG0H37QSDvcRhj4XylZwMLOJSc-I9jDwg',
    appId: '1:876289046371:ios:af566a7fbf1379ec934556',
    messagingSenderId: '876289046371',
    projectId: 'laci-495ab',
    storageBucket: 'laci-495ab.appspot.com',
    iosClientId: '876289046371-0usal196kdn9mj1p8k78qjn5b46e087h.apps.googleusercontent.com',
    iosBundleId: 'com.laci.systemleavesubmission',
  );
}
